package com.example.quizpulse_navigation.ui.quiz

import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.fragment.app.Fragment
import androidx.navigation.fragment.findNavController
import androidx.navigation.fragment.navArgs
import com.example.quizpulse_navigation.R
import com.example.quizpulse_navigation.data.Question
import com.example.quizpulse_navigation.databinding.FragmentQuizBinding
import dagger.hilt.android.AndroidEntryPoint

@AndroidEntryPoint
class QuizFragment : Fragment() {

    private var _binding: FragmentQuizBinding? = null
    private val binding get() = _binding!!

    // Receive SafeArgs — generated by SafeArgs Gradle plugin
    private val args: QuizFragmentArgs by navArgs()

    private val questions = listOf(
        Question(
            text = "What survives config changes?",
            answers = listOf("ViewModel", "LiveData", "Fragment", "Activity"),
            correct = 0
        ),
        Question(
            text = "Which class navigates between fragments?",
            answers = listOf("NavController", "FragmentManager", "Intent", "Router"),
            correct = 0
        ),
        Question(
            text = "SafeArgs prevents which error at compile time?",
            answers = listOf("Type mismatch", "NullPointerException", "StackOverflow", "ClassCast"),
            correct = 0
        )
    )

    private var currentIndex = 0
    private var score = 0

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        _binding = FragmentQuizBinding.inflate(inflater, container, false)
        return binding.root
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        // Access SafeArgs — type-safe, no cast needed
        binding.tvCategory.text = args.categoryName

        showQuestion()

        binding.btnSubmit.setOnClickListener {
            val selected = binding.rgAnswers.checkedRadioButtonId
            if (selected == -1) return@setOnClickListener

            val answerIndex = when (selected) {
                R.id.rb1 -> 0
                R.id.rb2 -> 1
                R.id.rb3 -> 2
                else -> 3
            }

            if (answerIndex == questions[currentIndex].correct) {
                score++
                currentIndex++
                if (currentIndex < questions.size) {
                    showQuestion()
                } else {
                    // Correct answer — navigate to Won screen with SafeArgs
                    val action = QuizFragmentDirections
                        .actionQuizFragmentToQuizWonFragment(
                            score = score,
                            total = questions.size
                        )
                    findNavController().navigate(action)
                }
            } else {
                // Wrong answer — game over
                val action = QuizFragmentDirections
                    .actionQuizFragmentToQuizFailedFragment()
                findNavController().navigate(action)
            }
        }
    }

    private fun showQuestion() {
        val q = questions[currentIndex]
        binding.tvQuestion.text = q.text
        binding.rb1.text = q.answers[0]
        binding.rb2.text = q.answers[1]
        binding.rb3.text = q.answers[2]
        binding.rb4.text = q.answers[3]
        binding.rgAnswers.clearCheck()
        binding.tvProgress.text =
            getString(R.string.placeholder_progress, currentIndex + 1, questions.size)
        
        // Update Progress Bar
        binding.progressBar.max = questions.size
        binding.progressBar.progress = currentIndex + 1
    }

    override fun onDestroyView() {
        super.onDestroyView()
        _binding = null
    }
}
